//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileRenamer.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileRenamer.Languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAllButtonText {
            get {
                return ResourceManager.GetString("ClearAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear selected items.
        /// </summary>
        public static string ClearButtonToolTip {
            get {
                return ResourceManager.GetString("ClearButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string ExecuteRenameButtonText {
            get {
                return ResourceManager.GetString("ExecuteRenameButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute the selected file renaming.
        /// </summary>
        public static string ExecuteRenameButtonToolTip {
            get {
                return ResourceManager.GetString("ExecuteRenameButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the fields Start No. and Increment with numbers only.
        /// </summary>
        public static string ExecuteRenameErrorMessage {
            get {
                return ResourceManager.GetString("ExecuteRenameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string ExtensionColumnHeader {
            get {
                return ResourceManager.GetString("ExtensionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a path for your desired folder or browse all folders.
        /// </summary>
        public static string FolderPathfToolTip {
            get {
                return ResourceManager.GetString("FolderPathfToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Path.
        /// </summary>
        public static string FolderPathText {
            get {
                return ResourceManager.GetString("FolderPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment by.
        /// </summary>
        public static string IncrementTBText {
            get {
                return ResourceManager.GetString("IncrementTBText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input.
        /// </summary>
        public static string InvalideInputTitle {
            get {
                return ResourceManager.GetString("InvalideInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark All.
        /// </summary>
        public static string MarkAllButtonText {
            get {
                return ResourceManager.GetString("MarkAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string MarkButtonText {
            get {
                return ResourceManager.GetString("MarkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an order for renaming.
        /// </summary>
        public static string MarkButtonToolTip {
            get {
                return ResourceManager.GetString("MarkButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameColumnHeader {
            get {
                return ResourceManager.GetString("NameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter file name.
        /// </summary>
        public static string NamingTextboxPlaceholder {
            get {
                return ResourceManager.GetString("NamingTextboxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the desired name.
        /// </summary>
        public static string NamingTextboxToolTip {
            get {
                return ResourceManager.GetString("NamingTextboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number to increment the numbering by (default  = 1).
        /// </summary>
        public static string NumberingIncrementTBToolTip {
            get {
                return ResourceManager.GetString("NumberingIncrementTBToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose whether the numbering should be before or after the name.
        /// </summary>
        public static string NumberingSwitchToolTip {
            get {
                return ResourceManager.GetString("NumberingSwitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Nr.
        /// </summary>
        public static string NumberingTextboxPlaceholder {
            get {
                return ResourceManager.GetString("NumberingTextboxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the starting number.
        /// </summary>
        public static string NumberingTextboxToolTip {
            get {
                return ResourceManager.GetString("NumberingTextboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenFolderDialogButtonText {
            get {
                return ResourceManager.GetString("OpenFolderDialogButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the file explorer for folder selection.
        /// </summary>
        public static string OpenFolderDialogButtonToolTip {
            get {
                return ResourceManager.GetString("OpenFolderDialogButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string OrderColumnHeader {
            get {
                return ResourceManager.GetString("OrderColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string PrefixText {
            get {
                return ResourceManager.GetString("PrefixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application needs to restart to apply language settings.
        /// </summary>
        public static string RestartMessage {
            get {
                return ResourceManager.GetString("RestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply language settings?.
        /// </summary>
        public static string RestartTitle {
            get {
                return ResourceManager.GetString("RestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string SelectionColumnHeader {
            get {
                return ResourceManager.GetString("SelectionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string SizeColumnHeader {
            get {
                return ResourceManager.GetString("SizeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        public static string SuffixText {
            get {
                return ResourceManager.GetString("SuffixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2 - Rename Files.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
